name: Sync to Backup Repository

on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Verify BACKUP_REPO_PAT environment variable
        run: |
          if [ -z "${{ secrets.BACKUP_REPO_PAT }}" ]; then
            echo "Error: BACKUP_REPO_PAT is not set."
            exit 1
          else
            echo "BACKUP_REPO_PAT is set."
          fi

      - name: Set up Git configuration
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"

      - name: Add backup repository as remote
        run: |
          git remote add backup https://username:${{ secrets.BACKUP_REPO_PAT }}@github.com/dalibendhiab10/R8-carav-backup.git

      - name: Push changes to backup repository
        run: |
          git push --mirror backup
