name: Sync to Backup Repository

on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Fetch entire history to avoid missing objects
          fetch-depth: 0

      - name: Set up Git configuration
        run: |
          git config user.name "dalibendhiab10"
          git config user.email "itsdalibendhiab10@gmail.com"

      - name: Add backup remote
        run: |
          # Add backup remote with authentication using PAT
          git remote add backup https://x-access-token:${{ secrets.BACKUP_REPO_PAT }}@github.com/dalibendhiab10/R8-carav-backup.git

      - name: Push changes to backup repository
        run: |
          # Mirror all references to the backup repository
          git push backup --mirror
