name: Sync to Backup Repository

on:
  push:
    branches:
      - main  # Ensure this matches your main repository's default branch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures all branches and history are available

      - name: Set up Git configuration
        run: |
          git config user.name "dalibendhiab10"
          git config user.email "itsdalibendhiab@gmail.com"

      - name: Add backup remote
        run: |
          echo "Adding backup remote..."
          git remote add backup https://dalibendhiab10:${{ secrets.BACKUP_REPO_PAT }}@github.com/dalibendhiab10/R8-carav-backup.git
          echo "Current remotes:"
          git remote -v

      - name: Push changes to backup repository
        run: |
          echo "Pushing changes to backup repository..."
          git push --mirror backup
