name: Sync to Backup Repository

on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source repository
        uses: actions/checkout@v4
        with:
          repository: R8-IEEE/R8-carav
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add backup repository as remote
        run: |
          git remote add backup https://github.com/dalibendhiab10/R8-carav-backup.git

      - name: Push to backup repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --mirror backup
