name: Sync to Backup Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Main Repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'R8-IEEE'
          repository: 'R8-carav'
          branch: 'main'
          access-token: ${{ secrets.BACKUP_REPO_PAT }}

      - name: Sync to Backup Repository
        run: |
          git remote set-url origin https://github.com/dalibendhiab10/R8-carav-backup.git
          git push --mirror
