name: Sync to Backup Repo

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  sync_backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Push to Backup Repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git remote add backup https://x-access-token:${{ secrets.BACKUP_REPO_PAT }}@github.com/dalibendhiab10/R8-carav-backup.git
          git push --mirror backup
