name: Sync to Backup Repository

on:
  push:
    branches:
      - main  # Adjust if your default branch is named differently

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Set up Git configuration
        run: |
          git config user.name "dalibendhiab10"
          git config user.email "itsdalibendhiab@gmail.com"

      - name: Add backup repository as remote
        run: |
          git remote add backup https://github.com/dalibendhiab10/R8-carav-backup.git

      - name: Push changes to backup repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --mirror backup
